### ISSUE TITLE
Accessing config in models.py isn't working

### ISSUE THREAD

**Issue by yong27** [nitely/django-djconfig#14]
When I access config in models.py or other views, it occurs `AttributeError: Attribute "backup_time" not found in config.`

I checked when the register_config method called, it seems to register after the models/forms loaded. How can I register_config first?

**Comment by nitely** [comment]
You can't access the config before your apps are loaded, this basically means you should not access any config attribute at import time.

```python
# module.py

# This will raise AttributeError
my_global = config.backup_time

def run_on_load():
    # This will raise AttributeError, see below
    if config.backup_time:
        pass
run_on_load()  # run on first import

class MyClass:
    # This will raise AttributeError
    my_class_attr = config.backup_time    # evaluated on first import
```

You should be able to access the config within methods and functions that are not called on import time.
