### ISSUE TITLE
How to save/recall config settings

### ISSUE THREAD

**Issue by tylerecouture** [nitely/django-djconfig#16]
Thanks for the awesome app! (I think..not quite working for me yet..)

I have it installed, and can get a form with some keys and values, but they won't save?  I'm just using the simple sample code you provided, but when I go back to the config form it has the initial values again instead of the updates values.

**Comment by nitely** [comment]
Did you [register the form](http://django-djconfig.readthedocs.org/en/latest/usage.html#registering-the-config-form)?

Try accessing one of the config values within the view, i.e:

```
from djconfig import config

def my_view(req):
    config.my_key
```

**Comment by tylerecouture** [comment]
Thanks! I had the wrong name when registering the form.

I tried using a ModelChoiceField and it threw an error:

```class MyConfigForm(ConfigForm):

   my_first_key = forms.BooleanField(required=False)
   my_second_key = forms.IntegerField()
   my_current_semester = forms.ModelChoiceField(queryset = Semester.objects.all())```

"Database is trying to update a relational field of type TextField with a value of type Semester. Make sure you are setting the correct relations"

Is this a limitation or another error on my part? Thanks for the replies!

**Comment by nitely** [comment]
That is a [limitation](http://django-djconfig.readthedocs.org/en/latest/fields.html#supported-form-fields).

Although, there is probably a workaround, this *may* work:

```python
class MyConfigForm(ConfigForm):

    my_first_key = forms.BooleanField(required=False)
    my_second_key = forms.IntegerField()
    my_current_semester = forms.ModelChoiceField(queryset = Semester.objects.all())

    def clean_my_current_semester(self):
        # Untested, may not even work
        return self.cleaned_data['my_current_semester'].pk
    
```

Let me know if it works.

**Comment by tylerecouture** [comment]
It works! That's so cool! =D

**Comment by nitely** [comment]
Great!

I'm leaving this open so I don't forget to *raise a exception if the form is not registered* when calling save().
