### ISSUE TITLE
images config

### ISSUE THREAD

**Issue by tylerecouture** [nitely/django-djconfig#26]
Do you know the best way to set an image with this app?  For example, I have a default logo that I want to be able to change using my config form.  Is this possible?  Would I need to create a model specifically for this and then use a ModelChoiceField?

**Comment by nitely** [comment]
mmh, seems doable. I'll push a fix later today.

**Comment by nitely** [comment]
See http://django-djconfig.readthedocs.io/en/latest/cookbook.html#image-field for usage

**Comment by nitely** [comment]
Remember to upgrade `pip install django-djconfig --upgrade`
