### ISSUE TITLE
Implement multi choice config values

### ISSUE THREAD

**Issue by garthwilliamson** [nitely/django-djconfig#29]
In several place in my project it would be very useful to be able to store multiple values in a single config field. For example, I'd like to be able to include None, One or Many groups in a config value using

registration_default_groups = forms.ModelMultiChoiceField(auth.models.Group.objects.all(), required=False).

I understand that this could be a lot of work. If you gave me some guidelines on how you'd store the data, I could have a go at doing it myself.

**Comment by nitely** [comment]
Hey,

That field requires a list of PKs (or model instances), IIRC. So, the way to store a list of things would be serializing it [0] [1] into JSON (i.e: `{'mc': [1, 4, 6]}` when saving it and deserializing it when passing it as an initial value.

There's not `deserialize` function right now, so just add it to `utils`.

Let me know if any question arises.

[0]: https://github.com/nitely/django-djconfig/blob/master/djconfig/forms.py#L53
[1]: https://github.com/nitely/django-djconfig/blob/master/djconfig/utils.py#L57
